# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: form-api
# app and org for use with dashboard.serverless.com
app: form-api
org: rodev

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  stage: dev
  profile: serverless-admin
  
plugins:
  - serverless-offline

functions:
  getAllForms:
    handler: src/components/forms/form.handler.getAll
    events:
      - http:
          path: /forms
          method: GET

  getForm:
    handler: src/components/forms/form.handler.get
    events:
      - http:
          path: /forms/{path}
          method: GET

  newForm:
    handler: src/components/forms/form.handler.create
    events:
      - http:
          path: /forms
          method: POST

  updateForm:
    handler: src/components/forms/form.handler.update
    events:
      - http:
          path: /forms/{path}
          method: PUT

  removeForm:
    handler: src/components/forms/form.handler.delete
    events:
      - http:
          path: /forms/{path}
          method: DELETE

